name: Angular CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      working-directory: frontend

    # Skipping tests as no .spec.ts files exist in the project
    # - name: Run Tests
    #   run: npm run test:run -- --browsers=ChromeHeadless

    - name: Build Project (Production)
      run: npm run build:prod
      working-directory: frontend
